### ISSUE TITLE
Checkbox selection problem

### ISSUE THREAD

**Issue by madhanssr** [tristandenyer/Clone-section-of-form-using-jQuery#5]
Hi, This cloning section of Form is very useful. but i am facing one issue in this.
While clicking the cloned checkbox caption, it automatically selecting the first checkboxes.
Please suggest for this issue.

**Comment by tristandenyer** [comment]
This is now fixed in the latest release! Let me know what you think.

**Comment by javedofhumber** [comment]
How to save the data into database using this plugin. Thanks.

**Comment by saikumarbitta** [comment]
any update on how save the data into database using php?

**Comment by tristandenyer** [comment]
I do not have instructions on how to save data into your database. I recommend reaching out to someone who is knowledgable in the subject. This plugin was originally developed for a project where a backend engineer was going to wire it up to a database. I have no experience in that area; only HTML, CSS and JS.
