### ISSUE TITLE
would you consider add support to chosen.js?

### ISSUE THREAD

**Issue by lasteye** [tristandenyer/Clone-section-of-form-using-jQuery#6]
occur a problem that the next select option is frozen when clone select option with chosen.js.

**Comment by tristandenyer** [comment]
Thanks for letting me know. I'll download it and look into it.

**Comment by suwarsoadi** [comment]
I really love your plugin.

Exactly as stated by lasteye, chosen.js does not work when in the clone, as well as the bootstrap-datepicker.js (github.com/eternicode/bootstrap-datepicker) and bootstrap-timepicker.js (github.com/jdewit/bootstrap- timepicker).

Hope you can revise your plugin to run properly when combined with three pulgin I mentioned.

Thank you so much for your nice plugin.
