### ISSUE TITLE
how can i  format the data that is submitted through ur plugin???

### ISSUE THREAD

**Issue by ngangchill** [tristandenyer/Clone-section-of-form-using-jQuery#7]
i just stucked and cant get any idea how too do it.

Source array:
  

      ["data"] => array(10) {
          ["type"] => string(10) "controller"
          ["name"] => string(3) "eg1"
          ["description"] => string(5) "desc1"
          ["type2"] => string(8) "function"
          ["name2"] => string(2) "c2"
          ["controller2"] => string(4) "welcome"
          ["description2"] => string(6) "desc 2"
          ["type3"] => string(10) "controller"
          ["name3"] => string(2) "c3"
          ["description3"] => string(8) "c3 descr"
        }

from the above array how can i get new array like:

       array(
         array(
           'type' => 'controller',
           'name' => 'eg1',
           'description' => 'desc1'
         ),
          array(
           'type' => 'function',
           'controller' => 'welcome',
           'name' => 'c2',
           'description' => 'desc 2'
         ),
         array(
           'type' => 'controller',
           'name' => 'eg1',
           'description' => 'desc1'
         ),
         array(
           'type' => 'controller',
           'name' => 'c3',
           'description' => 'c3 descr'
         )
       );

data is submitted through a https://github.com/tristandenyer/Clone-section-of-form-using-jQuery

thanks for help

**Comment by tristandenyer** [comment]
To be honest, I have no idea. Arrays are not something I know how to work with, and secondly, I don't know how to submit info from the form. Strange as it sounds, I built the form and this plugin, but I just shipped it to a backend engineer to hook it up to the database. (This was on a contract and I don't know who that engineer was.)

I recommend asking on Stackoverflow, someone there would know.

**Comment by ngangchill** [comment]
i got a solution from codeigniter forum.
     
            $source_data = $this->input->post();
            //get array keys
            $data_key = array_keys($source_data);
            //get last element of the array
            $data_last_string = end($data_key);
            //get the id no
            $max_id = $data_last_string[11];
 
                // array
                $count = 1;
                $checking = TRUE;
                $output_data = array();

                while ($checking) {
                    $temp_data = array();
                    if (isset($source_data['type' . $count])) {
                        $temp_data['resource_type'] = $source_data['type' . $count];
                    }

                    if (isset($source_data['name' . $count]) && isset($source_data['controller' . $count])) {
                        $temp_data['resource_controller'] = $source_data['controller' . $count];
                        $temp_data['resource_function'] = $source_data['name' . $count];
                    } else {
                        $temp_data['resource_controller'] = $source_data['name' . $count];
                    }
//                    if (isset($source_data['name' . $count])) {
//                        $temp_data['name'] = $source_data['name' . $count];
//                    }
//
//                    if (isset($source_data['controller' . $count])) {
//                        $temp_data['controller'] = $source_data['name' . $count];
//                    }

                    if (isset($source_data['description' . $count])) {
                        $temp_data['resource_description'] = $source_data['description' . $count];
                    }
                    if ($count == $max_id) {
                        $checking = FALSE;
                    }
                    if (count($temp_data) > 0) {
                        $output_data[] = $temp_data;
                    } else {
                        $checking = FALSE;
                    }

                    ++$count;
                }


## if there was a jquery plugin  for this repo... it will b great

thanks

**Comment by tristandenyer** [comment]
Thanks for letting all of us know! I'm sure there are others out there with the same problem.
